# The write half of the config generator (plan step 7): turns a
# sniff_dataset() inference list into a fully-optioned, self-documenting YAML
# config. Presentation rules live HERE, not in the sniffer (values vs
# presentation split): detected values are emitted live, defaults are emitted
# commented out, every vocabulary key appears exactly once (live xor
# commented), positional lists are always complete and carry a do-not-comment
# warning, and the file is created-only -- an existing config is never
# touched. Doc comments come from the vocabulary's own descriptions, so the
# emitted file cannot document keys differently from the package.

# -- YAML formatting helpers (shared with the global generator, step 8) --------

# Backslashes must be escaped BEFORE quotes: in a YAML double-quoted scalar a
# bare backslash starts an escape sequence, so an unescaped Windows path either
# fails the scanner (\d) or silently corrupts (\n, \t become control chars).
.y_quote <- function(s) {
  s <- gsub("\\", "\\\\", s, fixed = TRUE)
  paste0('"', gsub('"', '\\"', s, fixed = TRUE), '"')
}

.y_scalar <- function(v) {
  if (is.logical(v))   return(tolower(as.character(v)))
  if (is.numeric(v))   return(format(v, scientific = FALSE))
  .y_quote(as.character(v))
}

# Flow-style list: [a, b, c]; strings quoted.
.y_flow <- function(vec) {
  paste0("[", paste(vapply(vec, function(x)
    if (is.numeric(x)) format(x, scientific = FALSE) else .y_quote(x),
    character(1)), collapse = ", "), "]")
}

# Wrap a vocabulary description into '## ' doc-comment lines. The double hash
# distinguishes documentation from commented-out keys ('# key: value'), so a
# reader (and the tests) can tell the two apart at a glance.
.wrap_doc <- function(text, width = 76L) {
  words <- strsplit(text, " ", fixed = TRUE)[[1]]
  lines <- character(0); cur <- "##"
  for (w in words) {
    if (nchar(cur) + 1L + nchar(w) > width && cur != "##") {
      lines <- c(lines, cur); cur <- "##"
    }
    cur <- paste(cur, w)
  }
  c(lines, cur)
}

.vocab_doc <- function(key) {
  v <- .config_vocabulary()
  .wrap_doc(v$description[v$key == key])
}

# One emitted key: doc comment from the vocabulary, then the live line(s) or
# the commented-out line(s).
.emit_key <- function(key, value_lines, live) {
  c("", .vocab_doc(key), if (live) value_lines else paste0("# ", value_lines))
}

# The FWF ruler: the sample record over a character-position ruler, so widths
# can be corrected (or filled in, for packed files) by counting positions.
.ruler_lines <- function(sample_line) {
  len   <- nchar(sample_line)
  tens  <- paste(vapply(seq_len(len), function(i)
    if (i %% 10 == 0) as.character((i %/% 10) %% 10) else " ", character(1)),
    collapse = "")
  units <- paste(rep_len(c(1:9, 0), len), collapse = "")
  c("## Ruler -- character positions of the first data record:",
    paste0("##  ", tens),
    paste0("##  ", units),
    paste0("##  ", sample_line))
}

.positional_warning <- c(
  "## POSITIONAL LIST -- always keep one entry per physical column, in file",
  "## order. NEVER comment out a single entry: every entry below it would",
  "## shift onto the wrong column. To exclude a column from checks, leave it",
  "## here and omit it from expected_columns / rules instead.")

# -- the dataset-config emitter ------------------------------------------------

# Build the emitted lines from a sniff result. `sample_line` is the first
# data record, used for the FWF ruler.
.emit_dataset_config <- function(s, dataset_name, sample_line) {
  is_fwf <- identical(s$format, "fwf")
  types_known <- length(s$column_types) > 0

  lines <- c(
    "# dqcheckr dataset config -- generated by generate_dataset_config()",
    paste0("# from: ", s$path),
    "# Detected values are set live; optional settings are shown commented out",
    "# with their defaults. Uncomment and edit only what you want to change.",
    paste0('# Check your edits any time with: validate_config("',
           dataset_name, '")'))

  # -- identity
  lines <- c(lines,
    .emit_key("dataset_name", paste0("dataset_name: ", .y_quote(dataset_name)), TRUE),
    .emit_key("description",  'description: "describe this dataset"', FALSE))

  # -- file source
  lines <- c(lines,
    .emit_key("current_file", paste0("current_file: ", .y_quote(s$path)), TRUE),
    .emit_key("folder",        'folder: "path/to/deliveries/"', FALSE),
    .emit_key("previous_file", 'previous_file: "path/to/previous.csv"', FALSE))

  # -- structure
  lines <- c(lines,
    .emit_key("format",   paste0("format: ", .y_quote(s$format)), TRUE),
    .emit_key("encoding", paste0("encoding: ", .y_quote(s$encoding)), TRUE),
    .emit_key("delimiter",
              paste0("delimiter: ", .y_quote(s$delimiter %||% .default_read$delimiter)),
              live = !is_fwf && identical(s$provenance[["delimiter"]], "detected")),
    .emit_key("quote_char",
              paste0("quote_char: ", .y_quote(s$quote_char %||% .default_read$quote_char)),
              live = !is_fwf && identical(s$provenance[["quote_char"]], "detected")))

  # -- CSV columns: col_names + csv_skip
  ## col_names is live only when it must replace the file's header (duplicate
  ## names renamed) or the file has no header; otherwise the file's own header
  ## is used and the complete list is shown commented for reference.
  col_names_live <- !is_fwf && (!is.null(s$renamed_from) || identical(s$header, FALSE))
  cn <- s$col_names %||% c("col_1", "col_2")
  cn_lines <- c("col_names:",
                vapply(seq_along(cn), function(i) {
                  entry <- paste0("  - ", .y_quote(cn[i]))
                  orig  <- s$renamed_from[cn[i]]
                  if (!is.null(s$renamed_from) && !is.na(orig) && cn[i] %in% names(s$renamed_from))
                    entry <- paste0(entry, "   # was ", .y_quote(unname(orig)))
                  entry
                }, character(1)))
  lines <- c(lines, "", .positional_warning,
             .emit_key("col_names", cn_lines, live = col_names_live)[-1],
             .emit_key("csv_skip",
                       paste0("csv_skip: ", s$csv_skip),
                       live = !is_fwf && s$csv_skip > 0))

  # -- FWF structure
  fwf_widths_lines <- if (is_fwf && s$fwf_packed) {
    "fwf_widths: TODO   # packed file: no blank gutters to auto-detect"
  } else {
    paste0("fwf_widths: ", .y_flow(s$fwf_widths %||% c(5L, 10L)))
  }
  fwf_doc <- c("", if (is_fwf) .ruler_lines(sample_line),
               if (is_fwf) .positional_warning,
               if (is_fwf && s$fwf_packed) c(
                 "## This file is PACKED (columns touch with no blank gutters), so the",
                 "## widths could not be auto-detected. Count the character positions on",
                 "## the ruler above and replace TODO with the list of column widths,",
                 "## e.g. fwf_widths: [8, 12, 4]. Validation refuses to run while TODO",
                 "## remains."))
  lines <- c(lines, fwf_doc,
             .emit_key("fwf_widths", fwf_widths_lines, live = is_fwf))
  fn <- s$fwf_col_names %||% c("col_1", "col_2")
  lines <- c(lines,
    .emit_key("fwf_col_names",
              c("fwf_col_names:", paste0("  - ", .y_quote(fn))),
              live = is_fwf && !s$fwf_packed),
    .emit_key("fwf_skip", "fwf_skip: 0", FALSE))

  # -- columns and checks
  ec <- s$expected_columns
  lines <- c(lines,
    .emit_key("expected_columns",
              if (length(ec)) paste0("expected_columns: ", .y_flow(ec))
              else 'expected_columns: ["col_a", "col_b"]',
              live = length(ec) > 0))
  kc <- s$key_column_candidates
  lines <- c(lines,
    .emit_key("key_columns",
              if (length(kc)) paste0("key_columns: ", .y_flow(kc),
                                     "   # candidates unique in the sample -- confirm before uncommenting")
              else 'key_columns: ["id"]',
              live = FALSE))
  # Keys through .y_quote like every other emitted name: a header field such
  # as "Price: USD" (or one starting with # / [ / & / *) would otherwise
  # produce an unparseable or silently corrupted map line.
  ct_lines <- if (types_known)
    c("column_types:", paste0("  ", vapply(names(s$column_types), .y_quote,
                                           character(1)),
                              ": ", unname(s$column_types)))
  else
    c("column_types:", "  some_column: character")
  lines <- c(lines, .emit_key("column_types", ct_lines, live = types_known))

  lines <- c(lines,
    .emit_key("column_rules",
              c("column_rules:", "  some_column:", "    max_missing_rate: 0.05",
                "    min_value: 0", '    pattern: "^[A-Z0-9]+$"'), FALSE),
    .emit_key("rule_overrides",
              c("rule_overrides:", "  max_missing_rate: 0.05",
                "  min_row_count: 1"), FALSE),
    .emit_key("custom_checks_file", 'custom_checks_file: "custom_checks.R"', FALSE))

  # -- infrastructure (normally inherited from the global dqcheckr.yml)
  lines <- c(lines,
    .emit_key("snapshot_db",
              paste0("snapshot_db: ", .y_quote(.default_paths$snapshot_db)), FALSE),
    .emit_key("report_output_dir",
              paste0("report_output_dir: ", .y_quote(.default_paths$report_output_dir)), FALSE))

  lines
}

# -- the global-config emitter -------------------------------------------------

# Example values for rules whose absence means "check not run": shown in the
# commented block so the vocabulary is visible, with a note that unset = off.
.rule_examples <- list(
  max_z_score           = 3.5,
  iqr_fence_multiplier  = 1.5,
  max_row_count         = 1000000L,
  max_file_size_mb      = 500,
  column_order_severity = "warn"
)

.emit_global_config <- function() {
  rv    <- .rule_vocabulary()
  rules <- rv[rv$placement %in% c("rules", "both"), , drop = FALSE]

  rule_lines <- unlist(lapply(seq_len(nrow(rules)), function(i) {
    k <- rules$key[i]
    v <- rules$default[[i]] %||% .rule_examples[[k]]
    note <- if (!rules$has_default[i]) "   # example -- unset means the check is off"
            else ""
    c(.wrap_doc(rules$description[i]),
      paste0("#   ", k, ": ", .y_scalar(v), note))
  }))

  c("# dqcheckr global config -- generated by generate_global_config()",
    "# Deployment-wide settings shared by every dataset. Values set live below",
    "# are the built-in defaults, shown so they are visible and editable;",
    "# the commented default_rules block lists every rule with its default --",
    "# uncomment a line (strip the single leading '# ') to change it.",
    "# Per-dataset overrides go in each dataset's rule_overrides.",
    .emit_key("snapshot_db",
              paste0("snapshot_db: ", .y_quote(.default_paths$snapshot_db)), TRUE),
    .emit_key("report_output_dir",
              paste0("report_output_dir: ", .y_quote(.default_paths$report_output_dir)), TRUE),
    "", .vocab_doc("default_rules"),
    "# default_rules:",
    rule_lines)
}

#' Generate the global configuration file
#'
#' Writes a fully-optioned \code{dqcheckr.yml}: the shared infrastructure
#' paths set live to their built-in defaults (visible and editable), and a
#' commented \code{default_rules} block listing \emph{every} rule key with its
#' default value and description -- the full rule vocabulary in one place, so
#' thresholds can be changed by uncommenting a line rather than consulting the
#' manual. Rules with no default are shown with an example value and a note
#' that leaving them unset keeps the check off.
#'
#' \strong{Create-only}, like \code{\link{generate_dataset_config}}: an
#' existing \code{dqcheckr.yml} is never overwritten -- generation aborts with
#' \code{dqcheckr_config_exists} and the file is untouched.
#'
#' @param config_dir Character. Directory to write \code{dqcheckr.yml} into
#'   (created if absent). Defaults to \code{"."}.
#'
#' @return Invisibly, the path of the written config file.
#'
#' @examples
#' tmp <- file.path(tempdir(), "gen-global-demo")
#' cfg <- generate_global_config(config_dir = tmp)
#' yaml::read_yaml(cfg)$snapshot_db
#'
#' @export
generate_global_config <- function(config_dir = ".") {
  dir.create(config_dir, recursive = TRUE, showWarnings = FALSE)
  out <- file.path(config_dir, "dqcheckr.yml")
  if (file.exists(out))
    rlang::abort(paste0(
      "Config already exists and will not be overwritten: ", out,
      "\nGenerated configs are created once and then owned by hand edits ",
      "(the never-overwrite rule)."),
      class = c("dqcheckr_config_exists", "dqcheckr_error"))
  writeLines(.emit_global_config(), out)
  message("[dqcheckr] Global config written: ", out,
          "\n  Relative snapshot_db/report_output_dir resolve against the ",
          "working directory -- run from the deployment root.")
  invisible(out)
}

#' Generate a dataset config from a delivery file
#'
#' Sniffs the delivery (\code{\link{sniff_dataset}}) and writes a
#' fully-optioned, self-documenting YAML config: every config key appears,
#' detected values set live, optional settings commented out with their
#' defaults shown, each key documented with the same description the
#' validator's vocabulary uses. Duplicate header names arrive renamed
#' positionally (with \code{# was "..."} annotations and \code{csv_skip: 1});
#' fixed-width files get a character-position ruler comment above
#' \code{fwf_widths}, and a packed file (no detectable boundaries) gets
#' explicit \code{TODO} widths that \code{\link{validate_config}} refuses to
#' run until filled in.
#'
#' \strong{Create-only.} An existing config for the dataset is never
#' overwritten -- generation aborts with \code{dqcheckr_config_exists} and the
#' file is untouched. Once generated, a config is owned by hand edits; to
#' re-sniff a changed delivery, generate under a different name (or into a
#' scratch directory) and diff.
#'
#' @param path Character. Path to the delivery file to sniff.
#' @param config_dir Character. Directory to write \code{<dataset_name>.yml}
#'   into (created if absent). Defaults to \code{"."}.
#' @param dataset_name Character or \code{NULL}. Config identity; defaults to
#'   the delivery filename without extension, sanitised to
#'   \code{[A-Za-z0-9_-]}.
#'
#' @return Invisibly, the path of the written config file.
#'
#' @examples
#' tmp <- file.path(tempdir(), "gen-demo")
#' dir.create(tmp, showWarnings = FALSE)
#' f <- file.path(tmp, "orders.csv")
#' writeLines(c("id,amount", "A1,10", "A2,20"), f)
#' cfg <- generate_dataset_config(f, config_dir = tmp)
#' validate_config("orders", config_dir = tmp)$valid
#'
#' @export
generate_dataset_config <- function(path, config_dir = ".", dataset_name = NULL) {
  s <- sniff_dataset(path)
  # Emit the path in forward-slash form: valid on every platform R supports,
  # and far cleaner to hand-edit than a backslash-escaped Windows path.
  # chartr, not normalizePath: a relative path must STAY relative (deployments
  # sync across machines and rely on relative paths resolving per machine).
  s$path <- chartr("\\", "/", s$path)

  dataset_name <- dataset_name %||%
    gsub("[^A-Za-z0-9_-]", "_", tools::file_path_sans_ext(basename(path)))
  if (!.is_string(dataset_name))
    rlang::abort("`dataset_name` must be a non-empty string.",
                 class = c("dqcheckr_invalid_argument", "dqcheckr_error"))

  dir.create(config_dir, recursive = TRUE, showWarnings = FALSE)
  out <- file.path(config_dir, paste0(dataset_name, ".yml"))
  if (file.exists(out))
    rlang::abort(paste0(
      "Config already exists and will not be overwritten: ", out,
      "\nGenerated configs are created once and then owned by hand edits ",
      "(the never-overwrite rule). To re-sniff, pass a different ",
      "dataset_name or config_dir and diff the result."),
      class = c("dqcheckr_config_exists", "dqcheckr_error"))

  sample_line <- .read_head_lines(path, 1L, s$encoding)[1L]
  writeLines(.emit_dataset_config(s, dataset_name, sample_line), out)
  message("[dqcheckr] Config written: ", out,
          "\n  Review the commented options, then check with validate_config(\"",
          dataset_name, "\", config_dir = \"", config_dir, "\").")
  invisible(out)
}
